DROP DATABASE IF EXISTS juego;
CREATE DATABASE juego;

USE juego;

CREATE TABLE JUGADOR(

id INTEGER,
nombre VARCHAR(50),
pass VARCHAR(50),
correo VARCHAR(50),
edad INTEGER,
elo VARCHAR(50),

PRIMARY KEY (id)

)ENGINE= InnoDB;

INSERT INTO JUGADOR VALUES (1,'Kevin','cuchiyasu','kevin.alca@gmail.com',24, 'hierro');
INSERT INTO JUGADOR VALUES (2,'Edu','manedu','manedu.alca@gmail.com',22, 'oro');
INSERT INTO JUGADOR VALUES (3,'Carlos','elpapi','carlos@gmail.com',21,'plata');

CREATE TABLE PARTIDA(

id INTEGER,
duracion FLOAT,
ganador VARCHAR(10),
perdedor VARCHAR(10),
PRIMARY KEY (id)

)ENGINE= InnoDB;

INSERT INTO PARTIDA VALUES (1,12.5,'Kevin','Carlos');
INSERT INTO PARTIDA VALUES (2,20.32,'Kevin','Edu');

CREATE TABLE HISTORIAL(

JUGADOR INTEGER,
PARTIDA INTEGER,
puntuacion INTEGER,
asesinatos INTEGER,

FOREIGN KEY (JUGADOR) REFERENCES JUGADOR(id),
FOREIGN KEY (PARTIDA) REFERENCES PARTIDA(id)

)ENGINE= InnoDB;

INSERT INTO HISTORIAL VALUES(1,1,1000,0);
INSERT INTO HISTORIAL  VALUES(3,1,3900,3);
INSERT INTO HISTORIAL VALUES(3,1,700,2);
INSERT INTO HISTORIAL VALUES(1,2,2000,10);
INSERT INTO HISTORIAL VALUES(2,2,1900,5);
INSERT INTO HISTORIAL VALUES(3,2,1700,7);
